name: postgres2-playground
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.9.*
  - numpy=1.20.*
  - pandas=1.1.*
  - matplotlib=3.3.*
  - jupyterlab
  - pip=20.2.*
  - pip:
      - psycopg2==2.9.1
